
version: '3'

services:
    backenddrink:
        build:
            context: .
            dockerfile: ./backenddrink.DockerFile
        image: backenddrink/app
        ports:
            - "3000:3000"
        #     - "443:443"
        # environment:
        #     - 
        depends_on:
            - 'mongo'

    # MongoDB
    mongo:
        image: 'mongo'
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always
    # Mongo Express Web-based MongoDB admin interface
    # mongo_express:
    #     image: mongo-express
    #     container_name: mongo_express
    #     depends_on:
    #         - 'mongo'
    #     ports:
    #         - '8081:8081'
    #     restart: always